[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python-tools"
version = "0.0.0"
description = "Internal utilities"
requires-python = ">=3.9"

[project.scripts]
gdir = "gdir.cli:main"
