endpoints:
  default:
    transport: email
    options:
      smtp_server: smtp.example.com
      smtp_port: 465
      imap_server: imap.example.com
      imap_port: 993
      username: user@example.com
      password_env: FILE_EMAIL_PASSWORD
      to_addr: dest@example.com
      subject_prefix: "[FILE]"
